apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-docker
  labels:
    app: spring-boot-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-docker
  template:
    metadata:
      labels:
        app: spring-boot-docker
    spec:
      containers:
      - name: spring-boot-docker

#The tag of the image also should be incremented and consistent with the tag version in the build-deploy.yaml file

        image: tironelorence/spring-boot-docker:1.1
        ports:
          - containerPort: 8080