name: CTSE-Microservices-CI/CD-Pipeline

on:
  push:
    branches: [ main ]
#  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
    - name: Building Project
      run: mvn clean install
    - name: Building Docker Image
      run: docker build . --file Dockerfile --tag tironelorence/spring-boot-docker
