name: CTSE-Microservices-CI/CD-Pipeline

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
    - name: Building Project
      run: mvn clean install
    - name: Login to Docker
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Test del
      run: docker rmi tironelorence/spring-boot-docker

    - name: Building Docker Image
      run: docker build . --file Dockerfile --tag tironelorence/spring-boot-docker
    - name: Pushing Docker Image to Docker Hub
      run: docker push tironelorence/spring-boot-docker

    - id: "auth"
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GKE_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

# Setup gcloud CLI
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Use GCloud CLI
      run: gcloud info

# Get the GKE credentials so we can deploy to the cluster
    - run: gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone ${{ env.GKE_ZONE }}

    - name: Deploy
      run: kubectl apply -f deployment.yaml
